const arr = [1, 3, 0, 4, 5, 6, 7];
console.log(arr);

// arr.sort();
// console.log(arr.sort());

// console.log(arr);
// // arr.reverse() 
// console.log(arr.reverse());
// arr.pop(); last delete 
// console.log(arr.pop());
// console.log(arr);
// arr.push() last add
// console.log(arr.push('10'));
// console.log(arr);
// arr.shift()
// console.log(arr.shift());
// console.log(arr);
// arr.unshift()
// console.log(arr.unshift('123'));
// console.log(arr);
// arr.concat();
// console.log(arr.concat('123'));
// console.log(arr);
// arr.join()
// console.log(arr.join(' '));
// console.log(arr);



